name: Backend deployment
on:
  push:
    branches:
      - dev
      - qa
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select the branch to run the workflow'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - prod
          - master

permissions:
  id-token: write
  contents: read

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello, World!"
